### ISSUE TITLE
setup_cassandra Fix gpgkey error in yum task

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.cassandra#171]
##### SUMMARY

setup_cassandra throws an error on CentOS7 for Cassandra 2.2...

` "msg": "warning: /var/cache/yum/x86_64/7/cassandra_yum/packages/cassandra-2.2.19-1.noarch.rpm: Header V4 RSA/SHA256 Signature, key ID 7e3e87cb: NOKEY\n\n\nInvalid GPG Key from https://www.apache.org/dist/cassandra/KEYS: unknown public key algorithm 22 at 2\n",`

https://github.com/ansible-collections/community.cassandra/runs/3810482203?check_suite_focus=true

Temp fix:

```
- name: Install cassandra yum package
  yum:
    name: "{{ cassandra_yum_pkg }}"
    state: present
    disable_gpg_check: yes  # TODO - TEMP DIsable until bug fixed "Invalid GPG Key from https://www.apache.org/dist/cassandra/KEYS: unknown public key algorithm 22 at 2"
  when: ansible_os_family == 'RedHat'
  notify:
    - redhat_remove_cassandra
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
