### ISSUE TITLE
modules that can use multiple keyspaces or roles as input

### ISSUE THREAD

**Issue by ivnovi** [ansible-collections/community.cassandra#222]
##### SUMMARY
consider implementing modules that accept multiple items be it keyspaces or roles/users. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cassandra_keyspace, cassandra_role modules

##### ADDITIONAL INFORMATION
when you have more resources (keyspaces, roles) it takes significant amount of time to run playbook where single task is used to create/update all resources, since each task creates its own session. If you could create/update multiple resources with single module it will work much quicker, especially when verifying existing resources. I'm looking to implement this, and thinking either to implement it here as part of collection or continue with in-house modules we use already.

I'm not sure what is best way to structure configuration for such module so it is useful for more users and whether it is aligned with "ansible way". Example:
```yaml
- name: create all ks at once
  cassandra_keyspaces:
    login_host: ..
    ...
    keyspaces:
      - keyspace: ks1
        data_centres:
          dc1: 3
          dc2: 3
      - keyspace: ks2
        data_centres:
          dc1: 3
          dc2: 3
      ...
  cassandra_roles:
    roles:
      - name: rhys
        password: 'secret'
        state: present
        login: yes
        permissions:
          ks1:
            - "ALL PERMISSIONS"
...
      - name: john
        password: 'secret'
        state: present
        login: yes
        permissions:
          ks2:
            - "SELECT"
```

comparing what currently you should do, and it is not quick when you have more items
```yaml
- name: create all ks at once
  cassandra_keyspace:
    name: "{{ item['name'] }}"
    ...
  with_items: "{{ keyspaces }}"
- name: create all ks at once
  cassandra_role:
    name: "{{ item['name'] }}"
    ...
  with_items: "{{ roles }}"
```

it could be also single module for both so that you could do more checks to verify if keyspace exists before performing grants and similar logic, similar as single module already is used for roles+grants.
