### ISSUE TITLE
Handle changing passwords in cassandra.role

### ISSUE THREAD

**Issue by itskarlsson** [ansible-collections/community.cassandra#265]
##### SUMMARY
It would be nice to be able to change a role's password with cassandra.role. Currently we simply ignore the password if it differs from the password in the database.
The problem is that the password is salted and hashed, so to be able to compare it we need to use bcrypt and know how many hashing rounds the server uses.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cassandra.role

##### ADDITIONAL INFORMATION

Rerunning the same role twice with different passwords would change the password of the role.

```yaml
- name: update some existing role
  community.cassandra.cassandra_role:
    name: "SomeExistingRole"
    state: present
    login: yes
    password: "ANewPassword"
    super_user: no
    login_user: <login user>
    login_password: <login password>
  run_once: true
```
